//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeMasterSetting
    {
        public int FID { get; set; }
        public string Month_year { get; set; }
        public string Stu_Class { get; set; }
        public string Tuition_Fee { get; set; }
        public string Tuition_Fee_Percent { get; set; }
        public string Bus_Fee_Percent { get; set; }
        public string Late_Fee_Start { get; set; }
        public string Late_Fee { get; set; }
        public string Printing_charges { get; set; }
        public string Other_fee { get; set; }
        public string Other_Fee_Reference { get; set; }
    }
}
