//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class firstformview
    {
        public int FID { get; set; }
        public string SchoolName { get; set; }
        public string FIRSTADDRESS { get; set; }
        public string SECONDADDRESS { get; set; }
        public string CONTACTA { get; set; }
        public string CONTACTB { get; set; }
        public string CONTACTC { get; set; }
        public string FIRSTEMAIL { get; set; }
        public string SECONDEMAIL { get; set; }
        public string WEBSITE { get; set; }
        public byte[] LOGO { get; set; }
        public string COMMENTS { get; set; }
    }
}
