//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smartschooldbEntities : DbContext
    {
        public smartschooldbEntities()
            : base("name=smartschooldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADDMISSION> TBLADDMISSIONs { get; set; }
        public virtual DbSet<Tbladmissionprint> Tbladmissionprints { get; set; }
        public virtual DbSet<Tblclass> Tblclasses { get; set; }
        public virtual DbSet<Tblschoolsetting> Tblschoolsettings { get; set; }
        public virtual DbSet<TblSection> TblSections { get; set; }
        public virtual DbSet<TBLSTUDENTENRROL> TBLSTUDENTENRROLs { get; set; }
        public virtual DbSet<FeeMasterSetting> FeeMasterSettings { get; set; }
        public virtual DbSet<StudentFeeDetail> StudentFeeDetails { get; set; }
        public virtual DbSet<TransMaster> TransMasters { get; set; }
        public virtual DbSet<firstformview> firstformviews { get; set; }
        public virtual DbSet<TblTeacherInformation> TblTeacherInformations { get; set; }
        public virtual DbSet<TblacadmicSession> TblacadmicSessions { get; set; }
        public virtual DbSet<Tblclasssection> Tblclasssections { get; set; }
        public virtual DbSet<TbladdBus> TbladdBuses { get; set; }
        public virtual DbSet<Tblbusdestination> Tblbusdestinations { get; set; }
        public virtual DbSet<TBLUSER> TBLUSERs { get; set; }
        public virtual DbSet<UserDeatil> UserDeatils { get; set; }
        public virtual DbSet<Tblbusstop> Tblbusstops { get; set; }
    }
}
