//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeDetail
    {
        public int STID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> FID { get; set; }
        public string Tuition_Fee { get; set; }
        public string Bus_Fee { get; set; }
        public string Printing_Charges { get; set; }
        public string Other_Fee { get; set; }
        public string Late_Fee { get; set; }
        public string Total_Fee { get; set; }
        public string Discount { get; set; }
        public string Amount_Payable { get; set; }
        public string Amount_Paid { get; set; }
        public string Balance { get; set; }
        public string Status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
