//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADDMISSION
    {
        public int ID { get; set; }
        public string ADMISSION_FORM { get; set; }
        public string STUDENT_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string STUDENT_NIC { get; set; }
        public string FATHER_NIC { get; set; }
        public string GENDER { get; set; }
        public string RELIGION { get; set; }
        public string FATHER_OCCUPATION { get; set; }
        public Nullable<System.DateTime> ADMISSION_DATE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PLACE_BIRTH { get; set; }
        public string MONTHLY_INCOM { get; set; }
        public string CAST { get; set; }
        public string CELL_NO { get; set; }
        public string LANDLINE { get; set; }
        public string OTHER_NO { get; set; }
        public string CURRENT_ADDRESS { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string PREVIOUS_SCHOOL { get; set; }
        public string OBTAIN_MARKS { get; set; }
        public string TOTAL_MARKS { get; set; }
        public string BLOODGROUP { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<bool> ADMISSION_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public byte[] IMAGE { get; set; }
        public string CURRENTSESSION { get; set; }
        public int SID { get; set; }
        public string FATHER_EMAIL { get; set; }
        public Nullable<System.DateTime> STUDENT_DOB { get; set; }
        public string HOME_TEL { get; set; }
        public string FATHER_CAST { get; set; }
        public string FATHER_CELL_NO { get; set; }
        public string OFFICE_LANDLINE { get; set; }
        public string G_NAME { get; set; }
        public string G_CNIC { get; set; }
        public string G_CELL { get; set; }
        public string G_OCCUPATION { get; set; }
        public string G_MONTHLY_INCOM { get; set; }
        public string G_CELL_NO { get; set; }
        public string G_BUSINESS_ADDRESS { get; set; }
        public string G_EMAIL { get; set; }
        public string S_CELL_NO { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string BUSINESS_ADDRESS { get; set; }
        public string EDUCATION1 { get; set; }
        public string EDUCATION2 { get; set; }
        public string ADMISSIONNO1 { get; set; }
        public string ADMISSIONNO2 { get; set; }
        public string YEAR1 { get; set; }
        public string YEAR2 { get; set; }
        public string BOARD_INSTITUTION1 { get; set; }
        public string BOARD_INSTITUTION2 { get; set; }
        public string GRADE1 { get; set; }
        public string GRADE2 { get; set; }
        public string OBTAIN_MARKS1 { get; set; }
        public string OBTAIN_MARKS2 { get; set; }
        public string TOTAL_MARKS1 { get; set; }
        public string TOTAL_MARKS2 { get; set; }
        public string PERCENTAGE1 { get; set; }
        public string PERCENTAGE2 { get; set; }
        public string STUDENTNAME1 { get; set; }
        public string STUDENTNAME2 { get; set; }
        public string CLAS1 { get; set; }
        public string CLAS2 { get; set; }
        public string SCHOOLNAME1 { get; set; }
        public string SCHOOLNAME2 { get; set; }
        public string STUDENT_EMAIL_ADDRESS { get; set; }
    }
}
