//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAttendance
    {
        public int AID { get; set; }
        public Nullable<int> SYSID { get; set; }
        public Nullable<int> STDID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Attendance { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string Session { get; set; }
    }
}
