//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbladdBus
    {
        public int BusID { get; set; }
        public string Driver { get; set; }
        public string Busreg { get; set; }
        public string Model { get; set; }
        public string Vehicletype { get; set; }
        public string Seatcapacity { get; set; }
    }
}
