//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBUSSESMAPPING
    {
        public int ID { get; set; }
        public Nullable<int> BUSID { get; set; }
        public Nullable<int> BUSDESTINATION { get; set; }
        public Nullable<int> BUSSTOP { get; set; }
        public string OTHER { get; set; }
    }
}
