//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblclasssection
    {
        public int ID { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Teacher { get; set; }
        public string Maxstudent { get; set; }
        public string FloorId { get; set; }
        public string RoomNo { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string Fee { get; set; }
        public string Acadmic_Session { get; set; }
    }
}
