//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFEEMASTER
    {
        public int FID { get; set; }
        public string Month_Year { get; set; }
        public Nullable<int> STU_Class { get; set; }
        public Nullable<decimal> TUITION_FEE { get; set; }
        public Nullable<decimal> TUITION_FEE_PERCENT { get; set; }
        public Nullable<decimal> BUS_FEE_PERCENT { get; set; }
        public Nullable<decimal> LATE_FEE_START { get; set; }
        public Nullable<decimal> LATE_FEE { get; set; }
        public Nullable<decimal> OTHER_FEE { get; set; }
        public string OTHER_FEE_REFERENCE { get; set; }
        public Nullable<decimal> ADMISSION_FEE { get; set; }
    }
}
