//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDENTENRROL
    {
        public int ClassId { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public string CLASSNAME { get; set; }
        public string SECTION { get; set; }
        public string ACADMICSESSION { get; set; }
        public string CREATED_BY { get; set; }
        public string CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string UPDATED_DATE { get; set; }
        public string Group { get; set; }
        public string Medium { get; set; }
    }
}
