//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDENTFEEDETAIL
    {
        public int SFID { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<decimal> TUITION_FEE { get; set; }
        public Nullable<decimal> BUS_FEE { get; set; }
        public Nullable<decimal> PRINTING_CHARGES { get; set; }
        public Nullable<decimal> OTHER_FEE { get; set; }
        public Nullable<decimal> LATE_FEE { get; set; }
        public Nullable<decimal> TOTAL_FEE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public decimal AMOUNT_PAYABLE { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> FEE_DATE { get; set; }
        public string CREATEED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> SYSID { get; set; }
        public Nullable<decimal> ADMISSION_FEE { get; set; }
    }
}
