//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTeacherInformation
    {
        public int ID { get; set; }
        public string TEACHERNAME { get; set; }
        public string FATHERNAME { get; set; }
        public Nullable<decimal> CELLNO { get; set; }
        public Nullable<decimal> OTHERCONTACT { get; set; }
        public string GENDER { get; set; }
        public string SALAR { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> JOININGDATE { get; set; }
        public string QUALIFICATION { get; set; }
        public string POSITION { get; set; }
        public string TEACHINGEXP { get; set; }
        public string ADDRESS { get; set; }
        public string COMMENTS { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public byte[] TeachImage { get; set; }
    }
}
